Demo\ValueObject\ErrorResponse:
    exclusion_policy: ALL
    read_only: true
    access_type: public_method
    properties:
        errors:
            type: array
        errorCode:
            type: int
        totalErrors:
            type: integer